# Base WORKDIR => /
FROM --platform=linux/amd64 openjdk:24-jdk-slim
WORKDIR /app

# Define build-time argument
ARG imageName
ARG environment

# Set environment variable from ARG
ENV IMAGE_NAME=${imageName}
ENV ENVIRONMENT=${environment}

# Copy Jar from build context to /app directory in the image
COPY target/${IMAGE_NAME}.jar ${IMAGE_NAME}.jar

# Set the entry point
ENTRYPOINT ["sh", "-c", "java -Dspring.profiles.active=${ENVIRONMENT} -jar /app/${IMAGE_NAME}.jar"]
